# Generated by Django 4.1.6 on 2023-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectivePatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('severity_rate', models.IntegerField()),
                ('months_of_treatment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('jan_eating_behaviour', models.IntegerField()),
                ('feb_eating_behaviour', models.IntegerField()),
                ('mar_eating_behaviour', models.IntegerField()),
                ('apr_eating_behaviour', models.IntegerField()),
                ('may_eating_behaviour', models.IntegerField()),
                ('jun_eating_behaviour', models.IntegerField()),
                ('jul_eating_behaviour', models.IntegerField()),
                ('jan_self_harm', models.IntegerField()),
                ('feb_self_harm', models.IntegerField()),
                ('mar_self_harm', models.IntegerField()),
                ('apr_self_harm', models.IntegerField()),
                ('may_self_harm', models.IntegerField()),
                ('jun_self_harm', models.IntegerField()),
                ('jul_self_harm', models.IntegerField()),
                ('jan_mood', models.IntegerField()),
                ('feb_mood', models.IntegerField()),
                ('mar_mood', models.IntegerField()),
                ('apr_mood', models.IntegerField()),
                ('May_mood', models.IntegerField()),
                ('Jun_mood', models.IntegerField()),
                ('Jul_mood', models.IntegerField()),
                ('jan_social_interactions', models.IntegerField()),
                ('feb_social_interactions', models.IntegerField()),
                ('mar_social_interactions', models.IntegerField()),
                ('apr_social_interactions', models.IntegerField()),
                ('may_social_interactions', models.IntegerField()),
                ('jun_social_Interactions', models.IntegerField()),
                ('jul_social_Interactions', models.IntegerField()),
            ],
        ),
    ]
