# Generated by Django 4.1.6 on 2023-02-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_age_patientdata_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdata',
            old_name='Jul_mood',
            new_name='jul_mood',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='Jun_mood',
            new_name='jun_mood',
        ),
        migrations.RenameField(
            model_name='patientdata',
            old_name='May_mood',
            new_name='may_mood',
        ),
    ]
